remote_theme: pmarsceill/just-the-docs

aux_links:
  "Our project on GitHub":
    - "//github.com/SpecialEliteSNP/yagpdb-music-player"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


# Color scheme supports "light" (default) and "dark"
color_scheme: dark